### ISSUE TITLE
SQS Sensor with EC2 Role

### ISSUE THREAD

**Issue by satellite-no** [StackStorm-Exchange/stackstorm-aws#120]
Does the AWS SQS sensor work when the provided `aws.yaml` is set to the below?  Meaning the ec2 instance role is being used?  I keep getting an error for `InvalidClientTokenId`.

```yaml
---
region: "us-east-1"
aws_access_key_id: None
aws_secret_access_key: None
st2_user_data: ""

sqs_sensor:
  input_queues:
    - stacstormAlert.fifo

sqs_other:
  max_number_of_messages: 1
```

Error: 
```text
2022-06-09 20:50:27,308 ERROR [-] Sensor "AWSSQSSensor" run method raised an exception: An error occurred (InvalidClientTokenId) when calling the GetCallerIdentity operation: The security token included in the request is invalid..
```
