### ISSUE TITLE
region in config.yaml doesn't seem to work

### ISSUE THREAD

**Issue by bartwalczak1** [StackStorm-Exchange/stackstorm-aws#46]
hi there,
I came across an issue with config.yaml. Following instructions I've set region to eu-west-1 and I am trying to query info about particular instance in that region with no joy. 

St2 is running on instance located in eu-west-1. When I run aws.ec2_get_all_instances only instances from us-east-1 are returned (list doesn't include ec2's from other regions).
When I pass:
```st2 run aws.ec2_get_all_instances instance_ids="i-093c0bab6376e01b3"```

I can see following msg:
```
.
id: 5981ee96f15096193d782038
status: failed
parameters:
  instance_ids: i-093c0bab6376e01b3
result:
  exit_code: 1
  result: None
  stderr: "Traceback (most recent call last):\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py\", line 259, in <module>\n    obj.run()\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py\", line 155, in run\n    output = action.run(**self._parameters)\n  File \"/opt/stackstorm/packs/aws/actions/run.py\", line 20, in run\n    return self.do_method(module_path, cls, action, **kwargs)\n  File \"/opt/stackstorm/packs/aws/actions/lib/action.py\", line 142, in do_method\n    resultset = getattr(obj, action)(**kwargs)\n  File \"/opt/stackstorm/virtualenvs/aws/lib/python2.7/site-packages/boto/ec2/connection.py\", line 585, in get_all_instances\n    max_results=max_results)\n  File \"/opt/stackstorm/virtualenvs/aws/lib/python2.7/site-packages/boto/ec2/connection.py\", line 681, in get_all_reservations\n    [('item', Reservation)], verb='POST')\n  File \"/opt/stackstorm/virtualenvs/aws/lib/python2.7/site-packages/boto/connection.py\", line 1186, in get_list\n    raise self.ResponseError(response.status, response.reason, body)\nboto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Response><Errors><Error><Code>InvalidInstanceID.NotFound</Code><Message>The instance ID 'i-093c0bab6376e01b3' does not exist</Message></Error></Errors><RequestID>b3fc4420-1970-4f24-9c3f-d80b23dc40b9</RequestID></Response>\n"
```

please advise, thanks!
